# Generated by Django 4.2 on 2024-01-30 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conversation_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_chatroom_owner', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='storychat_participants', to=settings.AUTH_USER_MODEL)),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reel')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.story')),
            ],
        ),
        migrations.RemoveField(
            model_name='storychatroom',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='storychatroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='storychatroom',
            name='story',
        ),
        migrations.DeleteModel(
            name='ReelChatroom',
        ),
        migrations.DeleteModel(
            name='StoryChatroom',
        ),
    ]
