# Generated by Django 4.2 on 2024-02-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatroom_remove_storychatroom_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_make', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('software_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orientation', models.IntegerField(blank=True, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('exposureTime', models.FloatField(blank=True, null=True)),
                ('exposureValue', models.FloatField(blank=True, null=True)),
                ('fnumber', models.FloatField(blank=True, null=True)),
                ('focalLength', models.FloatField(blank=True, null=True)),
                ('xResolution', models.FloatField(blank=True, null=True)),
                ('yResolution', models.FloatField(blank=True, null=True)),
                ('brightness', models.FloatField(blank=True, null=True)),
                ('photo_parent', models.CharField(choices=[('story', 'Story'), ('reel', 'Reel')], max_length=5)),
                ('photo_parent_id', models.CharField(max_length=255)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
