# Generated by Django 4.2 on 2024-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_camera_imagemetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='software_version',
        ),
        migrations.AlterField(
            model_name='camera',
            name='company_make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
