# Generated by Django 4.2 on 2024-02-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_camera_software_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='reel_conversation',
            field=models.ManyToManyField(blank=True, null=True, related_name='reel_conversation', to='core.conversation'),
        ),
        migrations.AddField(
            model_name='story',
            name='story_conversation',
            field=models.ManyToManyField(blank=True, null=True, related_name='story_conversation', to='core.conversation'),
        ),
    ]
