# Generated by Django 4.2 on 2024-02-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reel_reel_conversation_story_story_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chatroom_owner_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
