# Generated by Django 4.2 on 2024-02-04 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_conversation_chatroom_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chatroom_participants',
            field=models.ManyToManyField(related_name='list_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='chatroom_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='reel',
            name='reel_conversation',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_conversation',
        ),
        migrations.AddField(
            model_name='reel',
            name='reel_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reel_conversation', to='core.conversation'),
        ),
        migrations.AddField(
            model_name='story',
            name='story_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_conversation', to='core.conversation'),
        ),
    ]
