# Generated by Django 4.2 on 2024-02-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_conversation_chatroom_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='reel_conversation',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_conversation',
        ),
        migrations.AddField(
            model_name='reel',
            name='reel_conversation',
            field=models.ManyToManyField(related_name='reel_conversation', to='core.conversation'),
        ),
        migrations.AddField(
            model_name='story',
            name='story_conversation',
            field=models.ManyToManyField(related_name='story_conversation', to='core.conversation'),
        ),
    ]
