# Generated by Django 4.2 on 2024-02-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_reel_reel_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='chatroom_owner_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='chatroom_participants',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='chatroom_status',
        ),
    ]
