# Generated by Django 4.2 on 2024-02-05 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_conversation_chatroom_owner_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chatroom_owner_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='chatroom_participants',
            field=models.ManyToManyField(related_name='list_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='chatroom_status',
            field=models.BooleanField(default=False),
        ),
    ]
