# Generated by Django 4.2 on 2024-02-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_conversation_chatroom_owner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='chatroom_status',
        ),
    ]
