# Generated by Django 4.2 on 2024-02-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_conversation_chatroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='reel_conversation',
            field=models.ManyToManyField(blank=True, related_name='reel_conversation', to='core.conversation'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_conversation',
            field=models.ManyToManyField(blank=True, related_name='story_conversation', to='core.conversation'),
        ),
    ]
