# Generated by Django 4.2 on 2024-02-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_reel_reel_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chatroom_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
