# Generated by Django 4.2 on 2025-02-15 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_conversation_chatroom_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedToWallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('story', 'Story Item'), ('reel', 'Reel')], max_length=5)),
                ('content_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
