# Generated by Django 4.2 on 2025-02-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_promotedtowallmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedtowallmodel',
            name='content_id',
            field=models.CharField(max_length=255),
        ),
    ]
