# Generated by Django 4.2 on 2025-02-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_promotedtowallmodel_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedtowallmodel',
            name='content_type',
            field=models.CharField(choices=[('story', 'Story'), ('reel', 'Reel')], max_length=5),
        ),
    ]
