# Generated by Django 4.2 on 2025-02-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_promotedtowallmodel_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('viewport_northeast_lat', models.FloatField(blank=True, null=True)),
                ('viewport_northeast_lng', models.FloatField(blank=True, null=True)),
                ('viewport_southwest_lat', models.FloatField(blank=True, null=True)),
                ('viewport_southwest_lng', models.FloatField(blank=True, null=True)),
                ('types', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
