# Generated by Django 4.2 on 2025-10-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_maplocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_data',
            field=models.CharField(default='Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='reel',
            name='image',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
