# Generated by Django 5.2.7 on 2025-10-14 20:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_imagemodel_image_data_alter_reel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.reel_image_file_path),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.story_image_file_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=core.models.profile_image_file_path),
        ),
    ]
