# Generated by Django 5.2.7 on 2025-10-22 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0020_alter_reel_image_alter_story_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('post_story', 'posted_story'), ('post_reel', 'posted_reel'), ('like', 'liked'), ('love', 'loved'), ('celebrate', 'celebrated'), ('unlike', 'unliked'), ('comment', 'commented'), ('follow', 'followed'), ('visit', 'visited')], max_length=32)),
                ('target_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_activi_created_347311_idx'), models.Index(fields=['actor', 'created_at'], name='core_activi_actor_i_b6c9e8_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='core_activi_target__cf6e59_idx')],
            },
        ),
    ]
