from django.contrib import admin
from core import models
# Register your models here.
admin.site.register(models.User)
admin.site.register(models.Tag)
admin.site.register(models.Story)
admin.site.register(models.Reel)
admin.site.register(models.ImageModel)
admin.site.register(models.StoryComment)
admin.site.register(models.UserToken)
admin.site.register(models.Reset)
admin.site.register(models.PromotedToWallModel)
admin.site.register(models.UserProfile)
admin.site.register(models.Friend)
admin.site.register(models.FriendshipRequest)
admin.site.register(models.Follow)
admin.site.register(models.Block)
admin.site.register(models.StoryFeed)
admin.site.register(models.StoryReactionActivityFeed)
admin.site.register(models.StoryCommentActivityFeed)
admin.site.register(models.ReelFeed)
admin.site.register(models.ReelReactionActivityFeed)
admin.site.register(models.ReelCommentActivityFeed)
admin.site.register(models.FriendStoryActivityFeed)
admin.site.register(models.FriendReelActivityFeed)
admin.site.register(models.ImageMetaData)
admin.site.register(models.Camera)
admin.site.register(models.ReelComment)
admin.site.register(models.Activity)